version: '3'
services:
  python:
    build: .
    volumes:
      - .:/src
    command: bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

volumes:
  preditions:
  models:
